# wayland
linux_display_server wayland

# cursor
cursor_trail 3
cursor_trail_decay 0.1 0.3

# font
font_family JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14
background_opacity 0.4

# window settings
initial_window_width 95c
initial_window_height 35c
window_padding_width 20
confirm_os_window_close 0

tab_bar_style fade
tab_fade 1
active_tab_font_style   bold
inactive_tab_font_style bold

# keybinds
map kitty_mod+t     new_tab_with_cwd

# includes
include current-theme.conf
