background {
    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    path = $WALLPAPER   # only png supported for now
    # blur_passes = 2 # 0 disables blurring
    # blur_size = 3
    # noise = 0.0117
    # contrast = 0.8916
    # brightness = 0.8172
    # vibrancy = 0.1696
    # vibrancy_darkness = 0.0
}

# Hour-Time
label {
    position = $y_offset, 0
    halign = center
    valign = center
    text = cmd[update:1000] echo -e "<span color='##$foreground'>$(date +'%H'):</span><span color='##$accent'>$(date +'%M')</span>"
    font_size = 100
    font_family = JetBrains Mono Nerd Font ExtraBold Italic
}

# Day-Date-Month
label {
    position = $y_offset, -80
    halign = center
    valign = center
    text = cmd[update:1000] echo "<span color='##$accent'>$(date '+%A')</span><span color='##$foreground'>, $(date '+%d %B')</span>"
    font_size = 22
    font_family = JetBrains Mono Nerd Font Bold
}

# Input field
input-field {
    position = $y_offset, -160
    halign = center
    valign = center
    size = 250, 60
    outline_thickness = 2
    rounding = 20
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba($accent)
    inner_color = rgba(1, 0, 3, 0.8)
    font_color = rgba(200, 200, 200, 0.75)
    fade_on_empty = true
    font_family = JetBrains Mono Nerd Font Mono
    placeholder_text = <i><span foreground="##CDD6F4DD">Введите пароль...</span></i>
    hide_input = false
}

shape {
    position = $y_offset, 0
    halign = center
    valign = center
    size = 540, 100%
    color = rgba(1, 0, 3, 1)
    rounding = 0
    border_size = 2
    border_color = rgba(255, 255, 255, 0.0)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(1, 0, 3, 1)
}

# Player status
label {
    position = $y_offset, 10
    text = cmd[update:1000] echo $($HOME/.config/hypr/scripts/player-status.sh)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono
    halign = center
    valign = bottom
}
