general {
    lock_cmd = pidof hyprlock || WALLPAPER="$(awww query | sed 's/.*image: //' | head -n 1)" foreground="rgb(255, 255, 255)" hyprlock
    before_sleep_cmd = wlr-randr --output eDP-1 --on; brightnessctl --device="asus::kbd_backlight" set 0; loginctl lock-session
    after_sleep_cmd = $HOME/.scripts/asus/ROGstartup.sh
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}
